export const runtime = 'edge'

import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase-server'
import type { CoreCapability, HiddenStrength } from '@/types'
import MentorFeedbackForm from './MentorFeedbackForm'

export default async function PublicProfilePage({ params }: { params: { token: string } }) {
  const supabase = createClient()

  // Look up share link — no auth required
  // Use maybeSingle() so missing/invalid tokens return null instead of throwing
  const { data: shareLink, error: linkError } = await supabase
    .from('share_links')
    .select('id, visibility, user_id, report_id')
    .eq('token', params.token)
    .maybeSingle()

  if (linkError || !shareLink || shareLink.visibility === 'private') notFound()

  // Fetch user and report — both can legitimately be missing
  const [{ data: user }, { data: report }] = await Promise.all([
    supabase.from('users').select('name').eq('id', shareLink.user_id).maybeSingle(),
    supabase.from('capability_reports').select('*').eq('id', shareLink.report_id).maybeSingle(),
  ])

  if (!report) notFound()

  const capabilities: CoreCapability[] = report.core_capabilities_json || []
  const hiddenStrengths: HiddenStrength[] = report.hidden_strengths_json || []
  const name = user?.name || 'This person'
  const canReview = shareLink.visibility === 'mentor'

  return (
    <div className="max-w-[720px] mx-auto px-6 py-10">
      {/* Header */}
      <div className="mb-8 pb-6 border-b border-[#E8E3DA]">
        <div className="inline-block text-xs font-semibold px-3 py-1 rounded-full bg-[#EBF5F3] text-[#3D8A7A] mb-4">
          {canReview ? 'Mentor Review — Shared with you' : 'Shared Profile'}
        </div>
        <h1 className="text-3xl mb-2" style={{ fontFamily: 'var(--font-lora)' }}>{name}'s Capability Profile</h1>
        {canReview && <p className="text-[#7A756F] text-sm leading-relaxed">You've been invited to validate this profile. No account needed.</p>}
      </div>

      {/* Summary */}
      <div className="p-5 bg-[#FDF0EA] border border-[#E07A5F] border-opacity-30 rounded-2xl mb-6">
        <div className="text-xs font-bold tracking-widest text-[#E07A5F] mb-3">CAPABILITY SUMMARY</div>
        <p className="leading-relaxed text-[15px]">{report.summary}</p>
      </div>

      {/* Core capabilities */}
      {capabilities.length > 0 && (
        <div className="mb-6">
          <div className="text-xs font-bold tracking-widest text-[#2D2926] mb-4">CORE CAPABILITIES</div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {capabilities.map(c => (
              <div key={c.title} className="p-4 bg-white border border-[#E8E3DA] rounded-xl">
                <div className="font-semibold text-sm mb-1">{c.title}</div>
                <div className="text-sm text-[#7A756F] leading-relaxed">{c.explanation}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Hidden strengths */}
      {hiddenStrengths.length > 0 && (
        <div className="mb-8">
          <div className="text-xs font-bold tracking-widest text-[#3D8A7A] mb-4">HIDDEN STRENGTHS</div>
          <div className="flex flex-col gap-3">
            {hiddenStrengths.map(h => (
              <div key={h.title} className="flex gap-3 p-4 bg-[#EBF5F3] rounded-xl">
                <div className="w-7 h-7 bg-[#3D8A7A] rounded-lg flex items-center justify-center text-white text-xs flex-shrink-0">◈</div>
                <div>
                  <div className="font-semibold text-sm mb-1">{h.title}</div>
                  <div className="text-sm text-[#7A756F] leading-relaxed">{h.explanation}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Mentor feedback form */}
      {canReview && <MentorFeedbackForm shareLinkId={shareLink.id} name={name} />}

      <div className="mt-8 pt-6 border-t border-[#E8E3DA] text-center">
        <p className="text-xs text-[#7A756F] leading-relaxed">
          This profile was generated by <strong>Capability Navigator</strong> — an AI-powered capability discovery platform. AI output is guidance, not a final judgement.
        </p>
      </div>
    </div>
  )
}
